export default {
    iptc_object_attribute_reference: 'text',
    iptc_object_name: 'text',
    iptc_subject_reference: 'chips',
    iptc_keywords: 'chips',
    iptc_special_instructions: 'textarea',
    iptc_date_created: 'date',
    iptc_time_created: 'time',
    iptc_byline: 'text',
    iptc_byline_title: 'text',
    iptc_city: 'text',
    iptc_sub_location: 'text',
    iptc_province_state: 'text',
    iptc_country_primary_location_code: 'text',
    iptc_country_primary_location_name: 'text',
    iptc_original_transmission_reference: 'text',
    iptc_headline: 'text',
    iptc_credit: 'text',
    iptc_source: 'text',
    iptc_copyright_notice: 'text',
    iptc_caption_abstract: 'textarea',
    iptc_writer_editor: 'text',
    iptc_application_record_version: 'integer',
};
